# Unless explicitly stated otherwise all files in this repository are licensed under the the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

version: "2.4"
services:
  
  mockagent:
    container_name: transport-mockagent
    image: transport-mockagent
    environment:
      - DD_TRACE_AGENT_PORT
      - DD_DOGSTATSD_PORT
      - DD_APM_RECEIVER_SOCKET
      - DD_DOGSTATSD_SOCKET
    volumes:
      - ./results/${TRANSPORT}/uds-volume/:/var/run/datadog
      - ./results/${TRANSPORT}/mockagent/snapshots:/snapshots
      - ./results/${TRANSPORT}/traces/:/var/log/traces
      - ./results/${TRANSPORT}/stats/:/var/log/stats
    ports:
      - "9126:9126/tcp"
         
  orchestrator:
    container_name: transport-orchestrator
    image: transport-orchestrator
    environment:
      - TRANSPORT_STRESS_TIMEOUT_MS
    volumes:
      - ./results/${TRANSPORT}/logs/:/var/log/datadog
    depends_on:
      - mockagent
        
  spammer:
    container_name: transport-spammer
    image: transport-spammer
    environment:
      - DD_AGENT_HOST
      - DD_TRACE_AGENT_PORT
      - DD_DOGSTATSD_PORT
      - DD_APM_RECEIVER_SOCKET
      - DD_DOGSTATSD_SOCKET
    volumes:
      - ./results/${TRANSPORT}/uds-volume/:/var/run/datadog
      - ./results/${TRANSPORT}/logs/tracer:/var/log/datadog
    depends_on:
      - orchestrator
  