# Unless explicitly stated otherwise all files in this repository are licensed under the the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

version: "2.4"
services:
  
  mockagent:
    container_name: mockagent
    image: transport_tests/mockagent
    environment:
      - DD_AGENT_HOST
      - DD_TRACE_AGENT_PORT
      - DD_APM_RECEIVER_SOCKET
    volumes:
      - ./shared/${TRANSPORT}/run/:/var/run/datadog
      - ./shared/${TRANSPORT}/logs/:/var/logs/datadog
    ports:
      - "7126:7126"
      - "7125:7125"
         
  orchestrator:
    container_name: orchestrator
    image: transport_tests/orchestrator
    volumes:
      - ./shared/${TRANSPORT}/logs/:/var/logs/datadog
    depends_on:
      - mockagent
        
  spammer:
    container_name: spammer
    image: transport_tests/spammer
    environment:
      - DD_AGENT_HOST
      - DD_TRACE_AGENT_PORT
    volumes:
      - ./shared/${TRANSPORT}/run/:/var/run/datadog
      - ./shared/${TRANSPORT}/logs/:/var/logs/datadog
    depends_on:
      - mockagent
      - orchestrator
  