# Unless explicitly stated otherwise all files in this repository are licensed under the the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

version: "2.4"
services:

  observer:
    image: datadog/docker-dd-agent
    links:
      - mockagent
      - spammer
    environment:
      - DD_APM_ENABLED=false
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:.*concurrent-spammer.*"
      - DD_LOG_LEVEL
      - DD_ENV
      - DD_API_KEY=$DD_API_KEY
      - DD_TAGS
      - DD_HOSTNAME=observer${TRACER}${TRANSPORT}conc${CONCURRENT_SPAMMERS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  mockagent:
    container_name: transport-mockagent
    image: transport-mockagent
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://${DD_AGENT_HOST}:5555"]
    #   interval: 1s
    #   start_period: 10s
    #   retries: 30
    environment:
      - DD_APM_RECEIVER_PORT
      - DD_DOGSTATSD_PORT
      - DD_APM_RECEIVER_SOCKET
      - DD_DOGSTATSD_SOCKET
      - DD_TEST_STALL_REQUEST_SECONDS
      - DD_LOG_LEVEL
      - DD_ENV
      - DD_API_KEY
      - DD_TAGS
      - DD_SERVICE
      - DD_VERSION
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_HEALTH_PORT=5555
      - DD_HOSTNAME=mockagent${TRACER}${TRANSPORT}conc${CONCURRENT_SPAMMERS}
      - DD_PROCESS_AGENT_ENABLED=false
      - DD_LOGS_ENABLED=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - ./tmp/uds-volume/:/var/run/datadog
    ports:
      - "5555:5555"
      - "6126:6126"
      - "6125:6125/udp"
    # cpu_count: 1
    cpus: 0.5
    # cpu_percent: 10
    # mem_limit: 100m

  spammer:
    container_name: transport-spammer
    image: transport-spammer
    environment:
      - DD_AGENT_HOST
      - DD_APM_RECEIVER_PORT
      - DD_TRACE_AGENT_PORT
      - DD_DOGSTATSD_PORT
      - DD_APM_RECEIVER_SOCKET
      - DD_DOGSTATSD_SOCKET
      - DD_TRACE_DEBUG
      - DD_SERVICE
      - DD_VERSION
      - DD_LOG_LEVEL
      - DD_ENV
      # - DD_TAGS
      - DD_TRACE_GLOBAL_TAGS
      # - DD_TRACE_SAMPLE_RATE=1
    volumes:
      - ./results/${TRANSPORT}/logs/tracer:/var/log/datadog
      - ./tmp/uds-volume/:/var/run/datadog
    depends_on:
      - mockagent

  concurrent-spammer:
    image: transport-spammer
    environment:
      - DD_AGENT_HOST
      - DD_TRACE_AGENT_PORT
      - DD_APM_RECEIVER_PORT
      - DD_DOGSTATSD_PORT
      - DD_APM_RECEIVER_SOCKET
      - DD_DOGSTATSD_SOCKET
      - DD_SERVICE
      - DD_VERSION
      - DD_ENV
      - DD_TRACE_GLOBAL_TAGS
    volumes:
      - ./tmp/uds-volume/:/var/run/datadog
    depends_on:
      - mockagent
