# Unless explicitly stated otherwise all files in this repository are licensed under the the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2021 Datadog, Inc.

version: "2.4"
services:
  
  mockagent:
    container_name: transport-mockagent
    image: transport-mockagent
    environment:
      - DD_APM_RECEIVER_PORT
      - DD_TRACE_AGENT_PORT
      - DD_DOGSTATSD_PORT
      - DD_APM_RECEIVER_SOCKET
      - DD_DOGSTATSD_SOCKET
      - DD_API_KEY
      - DD_ENV
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - ./results/uds-volume/:/var/run/datadog
      - ./results/${TRANSPORT}/mockagent/snapshots:/snapshots
    ports:
      - "9126:9126/tcp"
      - "9125:9125/udp"
    cpu_count: 1
    cpus: 0.3
    cpu_percent: 10
    mem_limit: 50m
         
  orchestrator:
    container_name: transport-orchestrator
    image: transport-orchestrator
    environment:
      - TRANSPORT_STRESS_TIMEOUT_MS
    volumes:
      - ./results/${TRANSPORT}/logs/:/var/log/datadog
    depends_on:
      - mockagent
        
  spammer:
    container_name: transport-spammer
    image: transport-spammer
    environment:
      - DD_AGENT_HOST
      - DD_TRACE_AGENT_PORT
      - DD_APM_RECEIVER_PORT
      - DD_DOGSTATSD_PORT
      - DD_APM_RECEIVER_SOCKET
      - DD_DOGSTATSD_SOCKET
      - DD_TRACE_DEBUG
      - DD_ENV
      - DD_SERVICE
      - DD_VERSION
    volumes:
      - ./results/uds-volume/:/var/run/datadog
      - ./results/${TRANSPORT}/logs/tracer:/var/log/datadog
    depends_on:
      - orchestrator
    cpu_count: 1
    cpus: 1
    cpu_percent: 80
    mem_limit: 100m
  