name: Run Stress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: ./build.sh dotnet realagent
      
    - name: Run TCPIP
      run: ./run.sh tcpip
      
    - name: Run UDS
      run: ./run.sh uds
      
    - name: Compress results
      run: tar -czvf results_dotnet.tar.gz $(ls | grep results)
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: results_dotnet
        path: results_dotnet.tar.gz
