name: Run Stress Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '42 * * * *' # 42nd minute of every hour

jobs:
  stress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - library: dotnet
          #   agent: mockagent
          #   concurrent: 5
            
          - library: dotnet
            agent: realagent
            concurrent: 0
            
          - library: dotnet
            agent: realagent
            concurrent: 1

          - library: dotnet
            agent: realagent
            concurrent: 5

          - library: dotnet
            agent: realagent
            concurrent: 10

          - library: dotnet
            agent: realagent
            concurrent: 20
            
          #- library: nodejs
          #  agent: realagent
          #  concurrent: DEFAULT
          
          #- library: python
          #  agent: realagent
          #  concurrent: DEFAULT
          
          #- library: golang
          #  agent: realagent
          #  concurrent: DEFAULT
            
          #- library: ruby
          #  agent: realagent
          #  concurrent: DEFAULT
            
          #- library: java
          #  agent: realagent
          #  concurrent: DEFAULT
            
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: ./build.sh ${{ matrix.library }} ${{ matrix.agent }}
      
    - name: Run TCPIP
      run: ./run.sh tcpip
      env:
        DEBUG_MODE: false
        RUN_ID: ${{ github.run_id }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        CONCURRENT_SPAMMERS: ${{ matrix.concurrent }}
        TRACER: ${{ matrix.library }}

    - name: TCPIP Spammer Logs
      run: ./show-logs.sh tcpip ${{ matrix.library }} spammer
         
    - name: TCPIP Agent Logs
      run: ./show-logs.sh tcpip ${{ matrix.library }} mockagent
      
    - name: Run UDS
      run: ./run.sh uds
      env:
        DEBUG_MODE: false
        RUN_ID: ${{ github.run_id }}
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        CONCURRENT_SPAMMERS: ${{ matrix.concurrent }}
        TRACER: ${{ matrix.library }}
        
    - name: UDS Spammer Logs
      run: ./show-logs.sh uds ${{ matrix.library }} spammer
         
    - name: UDS Agent Logs
      run: ./show-logs.sh uds ${{ matrix.library }} mockagent
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: results_${{ matrix.library }}_${{ matrix.agent }}
        path: results
