name: Run Stress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - library: dotnet
            agent: mockagent
          - library: nodejs
            agent: mockagent
          - library: python
            agent: mockagent
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: ./build.sh ${{ matrix.library }} ${{ matrix.agent }}
      
    - name: Run TCPIP
      run: ./run.sh tcpip
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
      
    - name: Run UDS
      run: ./run.sh uds
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: results_${{ matrix.library }}_${{ matrix.agent }}
        path: results
